### ISSUE TITLE
NPFG deviation from reference 

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ethz-asl/ethzasl_fw_px4#44]
**Problem Description**
When running https://github.com/ethz-asl/ethzasl_fw_px4/pull/39 sometimes when executing path following, NPFG will sometimes deviate largely until it is pulled back to the path (not always)

![image](https://user-images.githubusercontent.com/5248102/141106415-9dc35f83-53b3-47bc-8c9a-c1c3a07d2098.png)

Flight log: https://logs.px4.io/plot_app?log=af826970-0008-40b1-bb89-6fde91d25eb5

It seems to happen more offten after following long straight line segments, but not entirely sure

**Comment by tstastny** [comment]
@Jaeyoung-Lim did you find the root cause of this?

**Comment by Jaeyoung-Lim** [comment]
@tstastny Sorry for the late response.

This was something on myside that I was calculating the wrong signed error and was appearing only when there were consecutive low curvature segments since the feedforward was enough to correct the bug I introduced.

This has been now fixed in https://github.com/ethz-asl/ethzasl_fw_px4/tree/pr-develop-offboard-npfg
