### ISSUE TITLE
Maintain pinned relevant setup instructions for ETHZ PX4 FW

### ISSUE THREAD

**Issue by botmayank** [ethz-asl/ethzasl_fw_px4#57]
I am trying to set up the [ETHZ terrain navigation](https://github.com/ethz-asl/terrain-navigation) project locally on Ubuntu 20.04 with ROS noetic. I faced the issue that the paths for some PX4 setup files and packages are different in the official docs compared to the ETHZ PX4. 

The deviations from the official docs that I have had to do so far include: 

1. Building PX4 without --no-sim-tools flag to get the gazebo targets

```Bash
git clone https://github.com/ethz-asl/ethzasl_fw_px4.git --branch pr-hinwil-testing --recursive
cd ..
cd ethzasl_fw_px4
bash ./Tools/setup/ubuntu.sh

make px4_sitl gazebo
``` 

2. Paths for SITL gazebo setup.sh and the ROS package are different from the latest PX4. 

```Bash
px4_dir=~/ethzasl_fw_px4
source $px4_dir/Tools/simulation/gazebo/setup_gazebo.bash $px4_dir $px4_dir/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$px4_dir
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$px4_dir/Tools/simulation/gazebo/sitl_gazebo
export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins
```

Where should such documentation lie? My thought was that since we might eventually want to rebase `ethzasl_fw_px4` to upstream, it might be safer in the `terrain-navigation` repo, or should it lie in `ethzasl_fw_px4` itself? 

I propose we maintain the working build instructions in either of these places as a pinned working instruction copy to make it immune to upstream changes in PX4 docs/paths etc for reproducibility. 

I've seen a similar issue on the PX4 forums where somebody has struggled because of very similar reasons and similar outputs as my experience:
https://discuss.px4.io/t/mavros-posix-sitl-launch-is-neither-a-launch-file-in-package-px4-nor-is-px4-a-launch-file-name/30522

@Jaeyoung-Lim @Ryanf55

**Comment by Jaeyoung-Lim** [comment]
@botmayank Thanks for looking into the problems, and sorry that you had to jump through these hoops.

I think probably the specific setups issues you had go through seems more relevant to the specific branch we are using, I think having it under `terrain-navigation` initially would help get people use the package. 

Then we can take care of the upstream compatibility, so that people can just refer to the official documentation.

Does this sound like a reasonable path?

**Comment by botmayank** [comment]
Sounds good to me. Opened a PR here, please have a look: 
https://github.com/ethz-asl/terrain-navigation/pull/18/files
